baseURL = "https://rhvoice.hu/"
defaultContentLanguage = "hu"
defaultContentLanguageInSubdir = true
#sectionPagesMenu = "mainmenu"
title = "Magyar RHVoice"
theme = "cupper"

[params]
dateFormat = "2006. 1. 2."
copyright = "© Copyright 2024 Kirill Belousov <cyrmax@internet.ru>, Zvonimir Stanecic <zvonimirek222@yandex.com>, Till Nikolett <tillnikolett@gmail.com>"
footer = "© Copyright 2024 Kirill Belousov <cyrmax@internet.ru>, Zvonimir Stanecic <zvonimirek222@yandex.com>, Till Nikolett <tillnikolett@gmail.com>"

[params.contact]
email = "info@rhvoice.hu"

[params.urls]
nvdaDirectLink = "https://rhvoice.org/download/RHVoice-1.14.1.nvda-addon"
androidApp = "https://storage.cyrmax.ru/rhvoice/vce/rhvoice-lang-testing.apk"

[params.urls.Anna]
sample = "/samples/anna-pelda.wav"
sapi = "https://storage.cyrmax.ru/rhvoice/vce/RHVoice-voice-Hungarian-Anna-Beta-v4.1.1002.20-setup.exe"
nvda = "https://storage.cyrmax.ru/rhvoice/vce/RHVoice-voice-Hungarian-Anna-Beta-4.1.1002.11.nvda-addon"

[params.urls.Katalin]
sample = "/samples/katalin-pelda.wav"
sapi = "https://storage.cyrmax.ru/rhvoice/vce/RHVoice-voice-Hungarian-Katalin-Beta-v4.1.1002.20-setup.exe"
nvda = "https://storage.cyrmax.ru/rhvoice/vce/RHVoice-voice-Hungarian-Katalin-Beta-4.1.1002.11.nvda-addon"

[languages]
[languages.hu]
title = "Magyar RHVoice"
languageName = "Magyar"
weight = 1
contentDir = "content/hu"

[languages.en]
title = "Hungarian RHVoice"
languageName = "English"
weight = 2
contentDir = "content/en"
