baseURL = "https://rhvoice.hu/"
defaultContentLanguage = "hu"
defaultContentLanguageInSubdir = true
#sectionPagesMenu = "mainmenu"
title = "Magyar RHVoice"
theme = "cupper"

[params]
dateFormat = "2006. 1. 2."
copyright = "© Copyright 2024 Kirill Belousov <cyrmax@internet.ru>, Zvonimir Stanecic <zvonimirek222@yandex.com>, Till Nikolett <tillnikolett@gmail.com>"
footer = "© Copyright 2024 Kirill Belousov <cyrmax@internet.ru>, Zvonimir Stanecic <zvonimirek222@yandex.com>, Till Nikolett <tillnikolett@gmail.com>"

[params.contact]
email = "info@rhvoice.hu"

[params.urls]
nvdaDirectLink = "https://github.com/RHVoice/RHVoice/releases/download/1.18.2/RHVoice-1.18.201.nvda-addon"
androidApp = "https://storage.cyrmax.ru/rhvoice/vce/RHVoice-1.19.3-alpha-signed.apk"

[params.urls.Anna]
sample = "/samples/anna-pelda.wav"
sapi = "https://storage.cyrmax.ru/rhvoice/vce/RHVoice-voice-Hungarian-Anna-Beta-v4.3.1030.23-setup.exe"
nvda = "https://storage.cyrmax.ru/rhvoice/vce/RHVoice-voice-Hungarian-Anna-Beta-4.3.1030.12.nvda-addon"

[params.urls.Katalin]
sample = "/samples/katalin-pelda.wav"
sapi = "https://storage.cyrmax.ru/rhvoice/vce/RHVoice-voice-Hungarian-Katalin-v4.5.1030.23-setup.exe"
nvda = "https://storage.cyrmax.ru/rhvoice/vce/RHVoice-voice-Hungarian-Katalin-4.5.1030.12.nvda-addon"

[params.urls.Imre]
sample = "/samples/imre-pelda.wav"
sapi = "https://storage.cyrmax.ru/rhvoice/vce/RHVoice-voice-Hungarian-Imre-Hun-v4.1.1030.23-setup.exe"
nvda = "https://storage.cyrmax.ru/rhvoice/vce/RHVoice-voice-Hungarian-Imre-Hun-4.1.1030.12.nvda-addon"

[languages]
[languages.hu]
title = "Magyar RHVoice"
languageName = "Magyar"
weight = 1
contentDir = "content/hu"

[languages.en]
title = "Hungarian RHVoice"
languageName = "English"
weight = 2
contentDir = "content/en"
